name: bracu_errands
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animate_do: ^2.1.0
  auto_route: ^3.2.4
  bloc: ^8.0.3
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter_bloc: ^8.0.1
  flutter_config: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.3
  flutter_hooks: ^0.18.3
  flutter_screenutil: ^5.3.1
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^2.3.2
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  timeago: ^3.2.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^3.2.3
  build_runner: ^2.1.10
  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  very_good_analysis: ^2.4.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/icons/
